version: "3"
services:

  app:
    image: nextid
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure

    ports:
      - "9999:9999"
    volumes:
      - ".:/app"
    networks:
      - webnet
    depends_on:
      - "webnet"
volumes:
  db:
    
networks:
  webnet:
